version: '2'

services:

  jupyter:
    image: niicloudoperation/notebook
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jupyter
    networks:
      - default
      - wifi
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/wifi.git -b janog41 ; jupyter notebook --NotebookApp.token='wifi'"
    extra_hosts:
      - "vyos:192.168.14.3"
      - "munin:192.168.14.4"
      - "ap64:192.168.14.64"
    ports:
      - "8888:8888"

  vyos:
    image: mnagaku/vyos
    restart: always
    depends_on:
      - jupyter
    volumes:
      - /lib/modules:/lib/modules
    container_name: vyos
    networks:
      - default
      - wifi
    command: /sbin/init
    privileged: true
    extra_hosts:
      - "jupyter:192.168.14.2"
      - "munin:192.168.14.4"
      - "ap64:192.168.14.64"

  munin:
    image: shaf/munin-server
    restart: always
    depends_on:
      - vyos
    container_name: munin
    networks:
      - default
      - wifi
    environment:
      ALLOWED_HOSTS: "192.168.0.0/16"
      HOSTNAME: "munin-node"
      TZ: "Asia/Tokyo"
    extra_hosts:
      - "jupyter:192.168.14.2"
      - "vyos:192.168.14.3"
      - "ap64:192.168.14.64"
    ports:
      - "80:80"

networks:

  wifi:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "br14"
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
        - subnet: 192.168.14.0/24
          gateway: 192.168.14.1
